package standup

import (
	"bufio"
	"encoding/json"
	"io"
	"regexp"
	"strings"
)

// SessionDigest is the per-session distilled output. JSON tags match CONTRACT §1
// exactly. Cwd is an attribution helper used by Run; it is never emitted.
type SessionDigest struct {
	Branch     string    `json:"branch"`
	DomID      string    `json:"domId"`
	FirstTs    string    `json:"firstTs"`
	LastTs     string    `json:"lastTs"`
	MsgCount   int       `json:"msgCount"`
	HumanTurns []string  `json:"humanTurns"`
	CIEvents   []CIEvent `json:"ciEvents"`
	Actions    []string  `json:"actions"`

	Cwd string `json:"-"`
}

// CIEvent is a pipeline-level CI failure aggregate.
type CIEvent struct {
	Pipeline  string `json:"pipeline"`
	FailCount int    `json:"failCount"`
}

var domIDRe = regexp.MustCompile(`(?i)dom-(\d+)`)

// DeriveDomID returns "DOM-<n>" from a branch containing a (case-insensitive)
// dom-<digits> token, else "".
func DeriveDomID(branch string) string {
	m := domIDRe.FindStringSubmatch(branch)
	if m == nil {
		return ""
	}
	return "DOM-" + m[1]
}

var (
	buildkiteRe    = regexp.MustCompile(`buildkite\.com/[\w.-]+/([\w.-]+)/builds/\d+`)
	buildNumFailRe = regexp.MustCompile(`build #\d+ failed`)
)

// failureSignal reports whether the unit text carries a failure-state signal.
// The bare word FAIL/FAILED is intentionally NOT a signal.
func failureSignal(text string) bool {
	switch {
	case strings.Contains(text, `"state":"failed"`):
		return true
	case strings.Contains(text, `"state":"blocked"`):
		return true
	case strings.Contains(text, "conclusion: failure"):
		return true
	case strings.Contains(text, `"conclusion":"failure"`):
		return true
	case strings.Contains(text, "❌"): // ❌
		return true
	case buildNumFailRe.MatchString(text):
		return true
	}
	return false
}

// rawLine is the subset of a session log line we read.
type rawLine struct {
	Type      string         `json:"type"`
	Timestamp string         `json:"timestamp"`
	GitBranch string         `json:"gitBranch"`
	Cwd       string         `json:"cwd"`
	Message   rawMessage     `json:"message"`
	ToolUse   *toolUseResult `json:"toolUseResult"`
}

type toolUseResult struct {
	Stdout string `json:"stdout"`
	Stderr string `json:"stderr"`
}

type rawMessage struct {
	Role    string          `json:"role"`
	Content json.RawMessage `json:"content"`
}

type contentBlock struct {
	Type      string          `json:"type"`
	ToolUseID string          `json:"tool_use_id"`
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Content   json.RawMessage `json:"content"`
	Input     struct {
		Command string `json:"command"`
	} `json:"input"`
}

var humanWrapperContains = []string{
	"<command-name>",
	"<system-reminder>",
	"<command-message>",
	"<local-command-stdout>", // output of a `!`-prefixed local command, not a prompt
}

// injectedNoisePrefixes are CLI/system-injected user messages that are not the
// developer's own prompts (surfaced during dogfooding of real session logs).
var injectedNoisePrefixes = []string{
	"<local-command-caveat>",
	"Claude configuration file at", // "... is corrupted" notices injected by the CLI
	"Caveat: The messages below were generated by the user while running",
}

func isGenuineHumanTurn(s string) bool {
	if s == "" {
		return false
	}
	for _, p := range injectedNoisePrefixes {
		if strings.HasPrefix(s, p) {
			return false
		}
	}
	for _, w := range humanWrapperContains {
		if strings.Contains(s, w) {
			return false
		}
	}
	// hook wrappers
	if strings.Contains(s, "<hook>") || strings.Contains(s, "<user-prompt-submit-hook>") {
		return false
	}
	return true
}

// ParseSession streams the reader line-by-line (constant memory) and computes a
// SessionDigest per CONTRACT §1 rules.
func ParseSession(r io.Reader) (SessionDigest, error) {
	d := SessionDigest{
		HumanTurns: []string{},
		CIEvents:   []CIEvent{},
		Actions:    []string{},
	}

	// Buffer per tool_use_id: combined unit text (tool_result content + stdout + stderr).
	units := map[string]*strings.Builder{}
	pipelineFails := map[string]int{}
	pipelineOrder := []string{}

	var actionsSeen = map[string]bool{}

	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 16*1024*1024)

	for sc.Scan() {
		line := sc.Bytes()
		if len(strings.TrimSpace(string(line))) == 0 {
			continue
		}
		var l rawLine
		if err := json.Unmarshal(line, &l); err != nil {
			continue // tolerate malformed/non-relevant lines
		}

		if l.GitBranch != "" && d.Branch == "" {
			d.Branch = l.GitBranch
			d.DomID = DeriveDomID(l.GitBranch)
		}
		if l.Cwd != "" && d.Cwd == "" {
			d.Cwd = l.Cwd
		}

		if l.Timestamp != "" {
			if d.FirstTs == "" || l.Timestamp < d.FirstTs {
				d.FirstTs = l.Timestamp
			}
			if l.Timestamp > d.LastTs {
				d.LastTs = l.Timestamp
			}
		}

		switch l.Type {
		case "user":
			d.MsgCount++
			// content is either a plain string (human turn) or a list of blocks.
			if s, ok := asString(l.Message.Content); ok {
				if isGenuineHumanTurn(s) {
					d.HumanTurns = append(d.HumanTurns, s)
				}
				continue
			}
			// list of blocks: tool_result blocks contribute to unit text.
			blocks := asBlocks(l.Message.Content)
			for _, b := range blocks {
				if b.Type == "tool_result" && b.ToolUseID != "" {
					ub := unitFor(units, b.ToolUseID)
					ub.WriteString(stringifyContent(b.Content))
					ub.WriteString("\n")
				}
			}
			// toolUseResult attaches to the tool_use_id of this line's tool_result.
			if l.ToolUse != nil {
				for _, b := range blocks {
					if b.Type == "tool_result" && b.ToolUseID != "" {
						ub := unitFor(units, b.ToolUseID)
						ub.WriteString(l.ToolUse.Stdout)
						ub.WriteString("\n")
						ub.WriteString(l.ToolUse.Stderr)
						ub.WriteString("\n")
					}
				}
			}
		case "assistant":
			d.MsgCount++
			for _, b := range asBlocks(l.Message.Content) {
				if b.Type == "tool_use" && b.Name == "Bash" {
					cmd := b.Input.Command
					for _, action := range []string{"git push", "gh pr create", "gh pr merge"} {
						if strings.Contains(cmd, action) && !actionsSeen[action] {
							actionsSeen[action] = true
							d.Actions = append(d.Actions, action)
						}
					}
				}
			}
		}
	}
	if err := sc.Err(); err != nil {
		return d, err
	}

	// Evaluate CI units.
	for _, ub := range units {
		text := ub.String()
		m := buildkiteRe.FindStringSubmatch(text)
		if m == nil {
			continue
		}
		if !failureSignal(text) {
			continue
		}
		pipeline := m[1]
		if _, ok := pipelineFails[pipeline]; !ok {
			pipelineOrder = append(pipelineOrder, pipeline)
		}
		pipelineFails[pipeline]++
	}
	for _, p := range pipelineOrder {
		d.CIEvents = append(d.CIEvents, CIEvent{Pipeline: p, FailCount: pipelineFails[p]})
	}

	return d, nil
}

func unitFor(units map[string]*strings.Builder, id string) *strings.Builder {
	if b, ok := units[id]; ok {
		return b
	}
	b := &strings.Builder{}
	units[id] = b
	return b
}

// asString returns the string value of message.content if it is a JSON string.
func asString(raw json.RawMessage) (string, bool) {
	if len(raw) == 0 {
		return "", false
	}
	if raw[0] != '"' {
		return "", false
	}
	var s string
	if err := json.Unmarshal(raw, &s); err != nil {
		return "", false
	}
	return s, true
}

// asBlocks returns the content blocks if message.content is a JSON array.
func asBlocks(raw json.RawMessage) []contentBlock {
	if len(raw) == 0 || raw[0] != '[' {
		return nil
	}
	var blocks []contentBlock
	if err := json.Unmarshal(raw, &blocks); err != nil {
		return nil
	}
	return blocks
}

// stringifyContent renders a tool_result block's content (string or array) to text.
func stringifyContent(raw json.RawMessage) string {
	if len(raw) == 0 {
		return ""
	}
	if s, ok := asString(raw); ok {
		return s
	}
	// array of blocks or arbitrary JSON: stringify as-is.
	return string(raw)
}
